### ISSUE TITLE
unable to save Todo file to hard drive 

### ISSUE THREAD

**Issue by yddub** [mNantern/QTodoTxt#153] opened 2015-10-25 14:39 UTC
I tried QTodoTXT under OpenSUSE 13.2 64 bit from this [source](https://build.opensuse.org/package/show?project=utilities&package=qtodotxt) . After creating some tasks i want to save the tasks as a textfile under my harddrive, but QTodotxt will not save a file to the directory. So i started qtototxt from the terminal and i get this error after trying to save a file: 

Traceback (most recent call last):
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 163, in _view_onCloseEvent
    if self._canExit():
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 157, in _canExit
    self.save()
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 192, in save
    QtGui.QFileDialog.getSaveFileName(self._view, filter=FILENAME_FILTERS)
ValueError: too many values to unpack (expected 2)

**Comment by funkyfuture** [comment] 2015-11-01 20:00
duplicate of #147

**Closed by funkyfuture** 2015-11-01 20:00 UTC
